"""Agregar imagen a productos

Revision ID: 3accd47fcea7
Revises: 8b6d55a69e3a
Create Date: 2026-09-01 22:36:40.470893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3accd47fcea7'
down_revision = '8b6d55a69e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('imagen_tipo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('imagen_tipo')
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
