"""Agregar foto de perfil a usuarios

Revision ID: 8b6d55a69e3a
Revises: f78a515d6098
Create Date: 2026-08-31 23:42:57.789877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6d55a69e3a'
down_revision = 'f78a515d6098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil_tipo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil_tipo')
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
