"""Completar roles y permisos

Revision ID: ca77d64e0634
Revises: 39560428b596
Create Date: 2026-08-27 22:35:02.078172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca77d64e0634'
down_revision = '39560428b596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
